//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DP_dashboard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM12")]
        public string multiplexingComPort {
            get {
                return ((string)(this["multiplexingComPort"]));
            }
            set {
                this["multiplexingComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string plcComPort {
            get {
                return ((string)(this["plcComPort"]));
            }
            set {
                this["plcComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string dpComPort {
            get {
                return ((string)(this["dpComPort"]));
            }
            set {
                this["dpComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CalibrationStation")]
        public string StationType {
            get {
                return ((string)(this["StationType"]));
            }
            set {
                this["StationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public float PressureUnderTest1 {
            get {
                return ((float)(this["PressureUnderTest1"]));
            }
            set {
                this["PressureUnderTest1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public float PressureUnderTest2 {
            get {
                return ((float)(this["PressureUnderTest2"]));
            }
            set {
                this["PressureUnderTest2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public float PressureUnderTest3 {
            get {
                return ((float)(this["PressureUnderTest3"]));
            }
            set {
                this["PressureUnderTest3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public float PressureUnderTest4 {
            get {
                return ((float)(this["PressureUnderTest4"]));
            }
            set {
                this["PressureUnderTest4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.23")]
        public float PressureUnderTest5 {
            get {
                return ((float)(this["PressureUnderTest5"]));
            }
            set {
                this["PressureUnderTest5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.256")]
        public float PressureUnderTest6 {
            get {
                return ((float)(this["PressureUnderTest6"]));
            }
            set {
                this["PressureUnderTest6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.22")]
        public float PressureUnderTest7 {
            get {
                return ((float)(this["PressureUnderTest7"]));
            }
            set {
                this["PressureUnderTest7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.258")]
        public float PressureUnderTest8 {
            get {
                return ((float)(this["PressureUnderTest8"]));
            }
            set {
                this["PressureUnderTest8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2852")]
        public float PressureUnderTest9 {
            get {
                return ((float)(this["PressureUnderTest9"]));
            }
            set {
                this["PressureUnderTest9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.256599")]
        public float PressureUnderTest10 {
            get {
                return ((float)(this["PressureUnderTest10"]));
            }
            set {
                this["PressureUnderTest10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2741")]
        public float PressureUnderTest11 {
            get {
                return ((float)(this["PressureUnderTest11"]));
            }
            set {
                this["PressureUnderTest11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public float PressureUnderTest12 {
            get {
                return ((float)(this["PressureUnderTest12"]));
            }
            set {
                this["PressureUnderTest12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2222")]
        public float PressureUnderTest13 {
            get {
                return ((float)(this["PressureUnderTest13"]));
            }
            set {
                this["PressureUnderTest13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.29999")]
        public float PressureUnderTest14 {
            get {
                return ((float)(this["PressureUnderTest14"]));
            }
            set {
                this["PressureUnderTest14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2852")]
        public float PressureUnderTest15 {
            get {
                return ((float)(this["PressureUnderTest15"]));
            }
            set {
                this["PressureUnderTest15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public float TempUnderTest1 {
            get {
                return ((float)(this["TempUnderTest1"]));
            }
            set {
                this["TempUnderTest1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19.5")]
        public float TempUnderTest2 {
            get {
                return ((float)(this["TempUnderTest2"]));
            }
            set {
                this["TempUnderTest2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float TempUnderTest3 {
            get {
                return ((float)(this["TempUnderTest3"]));
            }
            set {
                this["TempUnderTest3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public float TempUnderTest4 {
            get {
                return ((float)(this["TempUnderTest4"]));
            }
            set {
                this["TempUnderTest4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public float TempUnderTest5 {
            get {
                return ((float)(this["TempUnderTest5"]));
            }
            set {
                this["TempUnderTest5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte TempControllerSlaveAddress {
            get {
                return ((byte)(this["TempControllerSlaveAddress"]));
            }
            set {
                this["TempControllerSlaveAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM6")]
        public string TempControllerComPort {
            get {
                return ((string)(this["TempControllerComPort"]));
            }
            set {
                this["TempControllerComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\work\\Rotal\\Rotal calibration\\project\\RotalCalib\\DP_dashboard\\bin\\Debug\\Logs")]
        public string LogPath {
            get {
                return ((string)(this["LogPath"]));
            }
            set {
                this["LogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\dudi9\\Desktop\\DPT.hex")]
        public string HexFilePath {
            get {
                return ((string)(this["HexFilePath"]));
            }
            set {
                this["HexFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Texas Instruments\\SmartRF Tools\\Flash Programmer\\bin\\Smart" +
            "RFProgConsole.exe")]
        public string FlashProgrammerToolPath {
            get {
                return ((string)(this["FlashProgrammerToolPath"]));
            }
            set {
                this["FlashProgrammerToolPath"] = value;
            }
        }
    }
}
